/*
  THIS FILE WAS AUTO GENERATED BY swagger-to-interaces (https://www.npmjs.com/package/swagger-to-interfaces).
  DO NOT EDIT OR COMMIT AS IT SHOULD BE GENERATED AS PART OF THE BUILD PROCESS.
*/

export default {
  getListAppUsingGET: {
    method: 'get',
    url: '/partner/app'
  },

  createAppUsingPOST: {
    method: 'post',
    url: '/partner/app',
    contentType: 'application/json'
  },

  getAppInfoUsingGET: {
    method: 'get',
    getUrl: (appId: number) => `/partner/app/${appId}`
  },

  updateAppInfoUsingPUT: {
    method: 'put',
    getUrl: (appId: number) => `/partner/app/${appId}`,
    contentType: 'application/json'
  },

  deleteAppUsingDELETE: {
    method: 'delete',
    getUrl: (appId: number) => `/partner/app/${appId}`
  },

  getListBannerUsingGET: {
    method: 'get',
    url: '/partner/banner'
  },

  getListUsingGET: {
    method: 'get',
    url: '/partner/category'
  },

  loginByUsernamePasswordUsingPOST: {
    method: 'post',
    url: '/partner/login',
    contentType: 'application/x-www-form-urlencoded'
  },

  logoutUsingDELETE: {
    method: 'delete',
    url: '/partner/logout'
  },

  getListOrderUsingGET: {
    method: 'get',
    url: '/partner/order'
  },

  createOrderUsingPOST: {
    method: 'post',
    url: '/partner/order',
    contentType: 'application/json'
  },

  renewOrderUsingPOST: {
    method: 'post',
    url: '/partner/order/renew',
    contentType: 'application/json'
  },

  searchListOrderUsingGET: {
    method: 'get',
    url: '/partner/order/search'
  },

  getOrganizationInfoUsingGET: {
    method: 'get',
    url: '/partner/organization'
  },

  updateOrganizationInfoUsingPUT: {
    method: 'put',
    getUrl: (organizationId: number) => `/partner/organization/organizationId`,
    contentType: 'application/json'
  },

  getOTPDefindByMailUsingGET: {
    method: 'get',
    url: '/partner/otp'
  },

  getListPackageUsingGET: {
    method: 'get',
    url: '/partner/package'
  },

  getPackageUsingGET: {
    method: 'get',
    getUrl: (packageId: number) => `/partner/package/packageId`
  },

  getPartnerInfoUsingGET: {
    method: 'get',
    url: '/partner/partner'
  },

  updatePartnerInfoUsingPUT: {
    method: 'put',
    url: '/partner/partner',
    contentType: 'application/json'
  },

  getListPartnerInfoUsingGET: {
    method: 'get',
    url: '/partner/partner/all'
  },

  updatePartnerInfoUsingPOST: {
    method: 'post',
    url: '/partner/partner/email/verify',
    contentType: 'application/json'
  },

  changePasswordPartnerUsingPOST: {
    method: 'post',
    url: '/partner/partner/password',
    contentType: 'application/json'
  },

  getPartnerInfoByIdUsingGET: {
    method: 'get',
    getUrl: (partnerId: string) => `/partner/partner/${partnerId}`
  },

  getListPermissionUsingGET: {
    method: 'get',
    url: '/partner/permission'
  },

  createPermissionUsingPOST: {
    method: 'post',
    url: '/partner/permission',
    contentType: 'application/json'
  },

  updatePermissionUsingPOST: {
    method: 'post',
    getUrl: (permissionId: number) => `/partner/permission/permissionId`,
    contentType: 'application/json'
  },

  getListServiceUsingGET: {
    method: 'get',
    url: '/partner/service'
  },

  getListServiceBoughtUsingGET: {
    method: 'get',
    url: '/partner/service/buy'
  },

  getServiceBoughtInfoUsingGET: {
    method: 'get',
    getUrl: (serviceId: number) => `/partner/service/buy/${serviceId}`
  },

  getServiceInfoUsingGET: {
    method: 'get',
    getUrl: (serviceId: number) => `/partner/service/${serviceId}`
  },

  signupUsingPOST: {
    method: 'post',
    url: '/partner/signup',
    contentType: 'application/json'
  },

  testUsingGET: {
    method: 'get',
    url: '/partner/test'
  },

  tokenUsingGET: {
    method: 'get',
    url: '/partner/test/token'
  }
}
