/*
  THIS FILE WAS AUTO GENERATED BY swagger-to-interaces (https://www.npmjs.com/package/swagger-to-interfaces).
  DO NOT EDIT OR COMMIT AS IT SHOULD BE GENERATED AS PART OF THE BUILD PROCESS.
*/

export interface AppDTO {
  bundle_android?: string
  bundle_ios?: string
  callback_url?: string
  created_time?: number
  id?: number
  name?: string
  secret_key?: string
  service_id?: number
  service_partner_id?: number
  status?: number
  total_request_used?: bigint
}

export interface BannerDTO {
  id?: number
  image?: string
  link?: string
  name?: string
  source?: string
  status?: number
  stt?: number
  type?: number
  view_point?: number
}

export interface CategoryDTO {
  active_status?: number
  css_icon?: string
  display_status?: number
  id?: number
  link_category?: string
  link_http?: string
  name?: string
  parent_id?: number
  stt?: number
}

export interface ChangePasswordPartnerRequest {
  new_password?: string
  old_password?: string
}

export interface CreateAppRequest {
  bundle_android?: string
  bundle_ios?: string
  name?: string
  service_id?: bigint
}

export interface CreateOrderRequest {
  package_id?: number
}

export interface CreatePermissionRequest {
  service_partner_id?: bigint
  sub_account_id?: bigint
}

export interface GetListPartnerInfoResponse {
  page?: number
  partners?: PartnerDTO[]
  size?: number
  total?: bigint
}

export interface PartnerDTO {
  avatar?: string
  created_time?: string
  display_name?: string
  email?: string
  email_confirmed_status?: number
  id?: string
  mobile?: string
  updated_time?: string
  username?: string
}

export interface OrganizationDTO {
  code?: string
  id?: number
  image?: string
  info?: string
  name?: string
  representative_email?: string
  representative_mobile?: string
  representative_name?: string
  root_account_email?: string
  root_account_id?: bigint
  status?: number
}

export interface OrderDTO {
  account_id?: bigint
  account_name?: string
  created_time?: bigint
  id?: bigint
  note?: string
  package_id?: number
  package_name?: string
  payment_info?: string
  payment_type?: number
  price_vnd?: bigint
  ref_service_partner_id?: bigint
  service_id?: number
  service_name?: string
  status?: number
  total_day?: number
  total_request?: bigint
  updated_time?: bigint
}

export interface PackageDTO {
  buy_status?: number
  description?: string
  from_date?: bigint
  id?: number
  image?: string
  name?: string
  payment_type?: number
  price_vnd?: bigint
  service_id?: number
  status?: number
  to_date?: bigint
  total_day?: number
  total_request?: bigint
}

export interface PermissionDTO {
  account_name?: string
  account_type?: number
  allow_status?: number
  id?: bigint
  service_id?: number
  service_name?: string
  service_partner_id?: bigint
  sub_account_id?: bigint
}

export interface RenewOrderRequest {
  package_id?: number
  service_partner_id?: bigint
}

export interface RAppDTO {
  code?: number
  data?: AppDTO
  msg?: string
  ts?: bigint
}

export interface RGetListPartnerInfoResponse {
  code?: number
  data?: GetListPartnerInfoResponse
  msg?: string
  ts?: bigint
}

export interface RListAppDTO {
  code?: number
  data?: AppDTO[]
  msg?: string
  ts?: bigint
}

export interface RListCategoryDTO {
  code?: number
  data?: CategoryDTO[]
  msg?: string
  ts?: bigint
}

export interface RListBannerDTO {
  code?: number
  data?: BannerDTO[]
  msg?: string
  ts?: bigint
}

export interface RListPackageDTO {
  code?: number
  data?: PackageDTO[]
  msg?: string
  ts?: bigint
}

export interface RListOrderDTO {
  code?: number
  data?: OrderDTO[]
  msg?: string
  ts?: bigint
}

export interface RListPermissionDTO {
  code?: number
  data?: PermissionDTO[]
  msg?: string
  ts?: bigint
}

export interface RListServiceBoughtDTO {
  code?: number
  data?: ServiceBoughtDTO[]
  msg?: string
  ts?: bigint
}

export interface ServiceBoughtDTO {
  account_id?: bigint
  active_date?: bigint
  buy_status?: number
  code?: string
  created_time?: bigint
  expired_date?: bigint
  id?: number
  image?: string
  info?: string
  link?: string
  name?: string
  service_partner_id?: number
  status?: number
  total_request?: number
  total_request_used?: number
}

export interface RListServiceDTO {
  code?: number
  data?: ServiceDTO[]
  msg?: string
  ts?: bigint
}

export interface ServiceDTO {
  buy_status?: number
  code?: string
  id?: number
  image?: string
  info?: string
  link?: string
  name?: string
  status?: number
}

export interface ROrganizationDTO {
  code?: number
  data?: OrganizationDTO
  msg?: string
  ts?: bigint
}

export interface RPackageDTO {
  code?: number
  data?: PackageDTO
  msg?: string
  ts?: bigint
}

export interface RPartnerDTO {
  code?: number
  data?: PartnerDTO
  msg?: string
  ts?: bigint
}

export interface RServiceBoughtDTO {
  code?: number
  data?: ServiceBoughtDTO
  msg?: string
  ts?: bigint
}

export interface RUserDTO {
  code?: number
  data?: UserDTO
  msg?: string
  ts?: bigint
}

export interface UserDTO {
  avatar?: string
  created_time?: string
  display_name?: string
  email?: string
  email_confirmed_status?: number
  id?: string
  mobile?: string
  organization_name?: string
  root_account_email?: string
  updated_time?: string
  username?: string
}

export interface RServiceDTO {
  code?: number
  data?: ServiceDTO
  msg?: string
  ts?: bigint
}

export interface Robject {
  code?: number
  data?: object
  msg?: string
  ts?: bigint
}

export interface SignupRequest {
  email?: string
  otp?: string
  password?: string
  username?: string
}

export interface UpdateAppRequest {
  bundle_android?: string
  bundle_ios?: string
  name?: string
  status?: number
}

export interface UpdateOrganizationRequest {
  image?: string
  info?: string
  name?: string
}

export interface UpdatePartnerRequest {
  email?: string
  mobile?: string
  nickname?: string
  picture?: string
}

export interface UpdatePermissionRequest {
  allow_status?: number
}

export interface RListRpRequestLogDTO {
  code: number
  data: RpRequestLogDTO[]
  msg: string
  ts: number
}
export interface RpRequestLogDTO {
  date: number
  month: number
  request_count: number
  service_id: number
}

export interface RPostCreateOrderDTO {
  code?: number
  data?: {
    id: number
  }
  msg?: string
  ts?: number
}

export interface BoughtPackageDTO {
  id: number
  service_id: number
  name: string
  price_vnd: number
  total_request: number
  buy_time: number
}

export interface RListRequestDTO {
  list: RequestDTO[]
  page: number
  size: number
  total: number
}

export interface RequestDTO {
  id: string
  log_id: number
  app_id: number
  app_name: string
  init_time: number
  time_duration: number
  response: string
}
