export const BASE_RESTAURANT_LINK = '/quan-ly-nha-hang'
export const BASE_TABLEFOOD_LINK = '/quan-ly-ban-an'
export const BASE_MENU_ITEM_LINK = '/quan-ly-thuc-don'
export const BASE_ORDER = '/quan-ly-dat-ban'
export const BASE_BILL = '/quan-ly-hoa-don'
